### ISSUE TITLE
cannot import name '_RUNNER_TASKS' from 'vllm.config.model'

### ISSUE THREAD

**Issue by NiuBlibing** [vllm-project/vllm-omni#534]
The latest version(0.13.0) of vllm doesn't have `_RUNNER_TASKS` config, which will leading import error.

```log
vllm-omni --help
INFO 12-30 09:35:08 [importing.py:44] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 12-30 09:35:08 [importing.py:68] Triton not installed or not compatible; certain GPU-related functions will not be available.
W1230 09:35:08.927000 7 site-packages/torch/utils/cpp_extension.py:117] No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/usr/local/bin/vllm-omni", line 4, in <module>
    from vllm_omni.entrypoints.cli.main import main
  File "/usr/local/lib/python3.13/site-packages/vllm_omni/__init__.py", line 23, in <module>
    from .config import OmniModelConfig
  File "/usr/local/lib/python3.13/site-packages/vllm_omni/config/__init__.py", line 5, in <module>
    from vllm_omni.config.model import OmniModelConfig
  File "/usr/local/lib/python3.13/site-packages/vllm_omni/config/model.py", line 11, in <module>
    from vllm.config.model import (
    ...<8 lines>...
    )
ImportError: cannot import name '_RUNNER_TASKS' from 'vllm.config.model' (/usr/local/lib/python3.13/site-packages/vllm/config/model.py)
```

 https://github.com/vllm-project/vllm-omni/blob/ebe37e9f571b79e2258d92a955818cf52b77f826/vllm_omni/config/model.py#L13

**Comment by hsliuustc0106** [comment]
currently, we work on vllm=0.12.0

**Comment by NiuBlibing** [comment]
> currently, we work on vllm=0.12.0

Oh, I'll try it.

**Comment by NiuBlibing** [comment]
And hope the limits could be removed for easier maintance.

> currently, we work on vllm=0.12.0

**Comment by hsliuustc0106** [comment]
> And hope the limits could be removed for easier maintance.
> 
> > currently, we work on vllm=0.12.0

we also hope so, but at this moment we cannot achieve it. in our installation guide, we always provide the specific vllm version at this moment.
