### PR TITLE
[Bugfix] Fix NPU Hunyuan fused MoE forward context after rebase to 0.18.0

### PR DESCRIPTION
**Pull request by Fishermanykx**
PLEASE FILL IN THE PR DESCRIPTION HERE ENSURING ALL CHECKLIST ITEMS (AT THE BOTTOM) HAVE BEEN CONSIDERED.

## Purpose
After upgrade to 0.18.0, running HunyuanImage-3.0 on NPU will report AttributeError: 'ForwardContext' object has no attribute 'num_tokens'

## Test Plan
Test env
```
vllm 0.18.0
vllm ascend commit id 1e05c4908f31737bc4eef865a9f351d030a77c9d
```

Online inference
```
vllm serve "/data/HunyuanImage-3.0/" --omni --port "8091" \
    --tensor_parallel_size 8  \
    --log-stats \
    --stage-configs-path "vllm_omni/model_executor/stage_configs/hunyuan_image3_moe_dit.yaml"
```
client
```
curl -X POST http://localhost:8091/v1/images/generations \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "A brown and white dog is running on the grass",
    "num_inference_steps": 50,
    "n": 1,
    "size": "1024x1024",
    "seed": 1234
  }' | jq -r '.data[0].b64_json' | base64 -d > output.png
```

## Test Result
output

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [ ] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [ ] The test plan. Please provide the test scripts & test commands. Please state the reasons if your codes don't require additional test scripts. For test file guidelines, please check the [test style doc](https://docs.vllm.ai/projects/vllm-omni/en/latest/contributing/ci/tests_style/)
- [ ] The test results. Please paste the results comparison before and after, or the e2e results.
- [ ] (Optional) The necessary documentation update, such as updating `supported_models.md` and `examples` for a new model. **Please run `mkdocs serve` to sync the documentation editions to `./docs`.**
- [ ] (Optional) Release notes update. If your change is user-facing, please update the release notes draft.
</details>

**BEFORE SUBMITTING, PLEASE READ <https://github.com/vllm-project/vllm-omni/blob/main/CONTRIBUTING.md>** (anything written below this line will be removed by GitHub Actions)

### CODE REVIEW

**Comment by Fishermanykx** [comment]
> LGTM. Doesn't GPU have the same issue?

This should be caused by the upgrade of vllm ascend, which leads to changes in the forward context. Since I don't have a GPU machine, I cannot confirm whether the corresponding issue exists on GPU.
