### ISSUE TITLE
[Bug]: Failed to deploy Qwen-Image on NPU

### ISSUE THREAD

**Issue by nuclearwu** [vllm-project/vllm-omni#357]
### Your current environment
vllm-ascend: 0.11.0
vllm-omni: the latest main branch

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

According to https://docs.vllm.ai/projects/vllm-omni/en/latest/user_guide/examples/online_serving/text_to_image/，I failed to deploy qwen-image on NPU. 
script：
```
export VLLM_WORKER_MULTIPROC_METHOD=spawn
MODEL_NAME_OR_PATH=/workspace/cache/aiops-sh2/johnjan/models/Qwen/Qwen-Image/

vllm serve ${MODEL_NAME_OR_PATH} \
    --served-model-name qwen-image \
    --omni \
    --port 8091
```
The following is the error log：
```
INFO 12-18 14:28:49 [group_coordinator.py:21] torch.npu synchronize
INFO 12-18 14:28:49 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_0d5ce54d'), local_subscribe_addr='ipc:///tmp/7577aae5-42e2-4175-9cba-40413e7b6e93', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 12-18 14:28:49 [npu_worker.py:138] Worker 0 created result MessageQueue
ERROR 12-18 14:31:00 [config.py:278] Error retrieving file list: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/Qwen/Qwen3-0.6B/tree/main?recursive=True&expand=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xfffc8d333890>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 0e239f87-d13c-4f9b-a30c-8a9c33450ef1)'), retrying 1 of 2
ERROR 12-18 14:33:13 [config.py:276] Error retrieving file list: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/Qwen/Qwen3-0.6B/tree/main?recursive=True&expand=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xfffc8d341b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 38e1264a-0efe-4768-aa8b-8a7a5e3d1a4d)')
Process DiffusionWorker-0:
Traceback (most recent call last):
  File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/worker/npu/npu_worker.py", line 224, in worker_main
    worker_proc = NPUWorkerProc(
                  ^^^^^^^^^^^^^^
  File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/worker/npu/npu_worker.py", line 141, in __init__
    worker = NPUWorker(
             ^^^^^^^^^^
  File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/worker/npu/npu_worker.py", line 46, in __init__
    self.init_device_and_model()
  File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/worker/npu/npu_worker.py", line 68, in init_device_and_model
    vllm_config = VllmConfig(model_config=ModelConfig(hf_config=_FakePretrainedConfig()), load_config=LoadConfig())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 121, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ModelConfig
  Value error, Invalid repository ID or local directory specified: 'Qwen/Qwen3-0.6B'.
Please verify the following requirements:
1. Provide a valid Hugging Face repository ID.
2. Specify a local directory that contains a recognized configuration file.
   - For Hugging Face models: ensure the presence of a 'config.json'.
   - For Mistral models: ensure the presence of a 'params.json'.
3. For GGUF: pass the local path of the GGUF checkpoint.
   Loading GGUF from a remote repo directly is not yet supported.
 [type=value_error, input_value=ArgsKwargs((), <unprintable dict object>), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error
(APIServer pid=30159) ERROR 12-18 14:33:16 [diffusion_engine.py:133] Rank 0 scheduler is dead. Please check if there are relevant logs.
corrupted size vs. prev_size
(APIServer pid=30159) ERROR 12-18 14:33:23 [diffusion_engine.py:135] Exit code: -6
(APIServer pid=30159) Traceback (most recent call last):
(APIServer pid=30159)   File "/usr/local/python3.11.13/bin/vllm", line 7, in <module>
(APIServer pid=30159)     sys.exit(main())
(APIServer pid=30159)              ^^^^^^
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/cli/main.py", line 51, in main
(APIServer pid=30159)     args.dispatch_function(args)
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/cli/serve.py", line 52, in cmd
(APIServer pid=30159)     uvloop.run(omni_run_server(args))
(APIServer pid=30159)   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 92, in run
(APIServer pid=30159)     return runner.run(wrapper())
(APIServer pid=30159)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "/usr/local/python3.11.13/lib/python3.11/asyncio/runners.py", line 118, in run
(APIServer pid=30159)     return self._loop.run_until_complete(task)
(APIServer pid=30159)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
(APIServer pid=30159)   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 48, in wrapper
(APIServer pid=30159)     return await main
(APIServer pid=30159)            ^^^^^^^^^^
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/openai/api_server.py", line 67, in omni_run_server
(APIServer pid=30159)     await omni_run_diffusion_server_worker(listen_address, sock, args, **uvicorn_kwargs)
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/openai/api_server.py", line 90, in omni_run_diffusion_server_worker
(APIServer pid=30159)     async with build_async_diffusion(args) as diffusion_engine:
(APIServer pid=30159)   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 210, in __aenter__
(APIServer pid=30159)     return await anext(self.gen)
(APIServer pid=30159)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/openai/api_server.py", line 261, in build_async_diffusion
(APIServer pid=30159)     diffusion_engine = AsyncOmniDiffusion(**diffusion_kwargs)
(APIServer pid=30159)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/async_diffusion.py", line 76, in __init__
(APIServer pid=30159)     self.engine: DiffusionEngine = DiffusionEngine.make_engine(od_config)
(APIServer pid=30159)                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/diffusion_engine.py", line 70, in make_engine
(APIServer pid=30159)     return DiffusionEngine(config)
(APIServer pid=30159)            ^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/diffusion_engine.py", line 34, in __init__
(APIServer pid=30159)     self._make_client()
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/diffusion_engine.py", line 79, in _make_client
(APIServer pid=30159)     processes, result_handle = self._launch_workers(
(APIServer pid=30159)                                ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "/vllm-workspace/vllm-omni/vllm_omni/diffusion/diffusion_engine.py", line 131, in _launch_workers
(APIServer pid=30159)     data = reader.recv()
(APIServer pid=30159)            ^^^^^^^^^^^^^
(APIServer pid=30159)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/connection.py", line 250, in recv
(APIServer pid=30159)     buf = self._recv_bytes()
(APIServer pid=30159)           ^^^^^^^^^^^^^^^^^^
(APIServer pid=30159)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/connection.py", line 430, in _recv_bytes
(APIServer pid=30159)     buf = self._recv(4)
(APIServer pid=30159)           ^^^^^^^^^^^^^
(APIServer pid=30159)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/connection.py", line 399, in _recv
(APIServer pid=30159)     raise EOFError
(APIServer pid=30159) EOFError
corrupted size vs. prev_size
examples/run_qwen_image.sh: line 7: 30159 Aborted                 (core dumped) vllm serve ${MODEL_NAME_OR_PATH} --served-model-name qwen-image --omni --port 8091
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://vllm-omni.readthedocs.io), which can answer lots of frequently asked questions.

**Comment by hsliuustc0106** [comment]
any env and logs?

**Comment by nuclearwu** [comment]
> any env and logs?

supplemented @hsliuustc0106

**Comment by hsliuustc0106** [comment]
I think this problem results from NPU is not adpative to online serving for diffusion models yet, please use offline at this moment. Next month we are going to deprecate the NPU workers and formalize the hardware plugin system.

**Comment by gcanlin** [comment]
Here is the similar issue and temporary solution: https://github.com/vllm-project/vllm-omni/issues/208#issuecomment-3615829963.

After upgrading to v0.12.0, this issue will be resolved.

**Comment by nuclearwu** [comment]
> Here is the similar issue and temporary solution: [#208 (comment)](https://github.com/vllm-project/vllm-omni/issues/208#issuecomment-3615829963).
> 
> After upgrading to v0.12.0, this issue will be resolved.

I switched to vllm-ascend v0.12.0.rc1, but also report error:
```
root@pod-1451157467256647680:/vllm-workspace/vllm-omni# bash examples/run_qwen_image.sh 
INFO 12-18 15:52:10 [__init__.py:43] Available plugins for group vllm.platform_plugins:
INFO 12-18 15:52:10 [__init__.py:45] - ascend -> vllm_ascend:register
INFO 12-18 15:52:10 [__init__.py:48] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-18 15:52:10 [__init__.py:217] Platform plugin ascend is activated
/usr/local/python3.11.13/lib/python3.11/site-packages/torch/amp/autocast_mode.py:266: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
Modular Diffusers is currently an experimental feature under active development. The API is subject to breaking changes in future releases.
INFO 12-18 15:52:17 [importing.py:68] Triton not installed or not compatible; certain GPU-related functions will not be available.
Traceback (most recent call last):
  File "/usr/local/python3.11.13/bin/vllm", line 3, in <module>
    from vllm_omni.entrypoints.cli.main import main
  File "/vllm-workspace/vllm-omni/vllm_omni/__init__.py", line 23, in <module>
    from .config import OmniModelConfig
  File "/vllm-workspace/vllm-omni/vllm_omni/config/__init__.py", line 5, in <module>
    from vllm_omni.config.model import OmniModelConfig
  File "/vllm-workspace/vllm-omni/vllm_omni/config/model.py", line 34, in <module>
    import vllm_omni.model_executor.models as me_models
  File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/__init__.py", line 1, in <module>
    from .qwen3_omni import Qwen3OmniMoeForConditionalGeneration
  File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/qwen3_omni/__init__.py", line 1, in <module>
    from .qwen3_omni import Qwen3OmniMoeForConditionalGeneration
  File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/qwen3_omni/qwen3_omni.py", line 31, in <module>
    from .qwen3_omni_moe_thinker import (
  File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/qwen3_omni/qwen3_omni_moe_thinker.py", line 74, in <module>
    from vllm.model_executor.models.qwen2_5_vl import (
ImportError: cannot import name 'Qwen2_5_VisionRotaryEmbedding' from 'vllm.model_executor.models.qwen2_5_vl' (/vllm-workspace/vllm/vllm/model_executor/models/qwen2_5_vl.py)
[ERROR] 2025-12-18-15:52:17 (PID:5544, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
```

**Comment by gcanlin** [comment]
> > Here is the similar issue and temporary solution: [#208 (comment)](https://github.com/vllm-project/vllm-omni/issues/208#issuecomment-3615829963).
> > After upgrading to v0.12.0, this issue will be resolved.
> 
> I switched to vllm-ascend v0.12.0.rc1, but also report error:
> 
> ```
> root@pod-1451157467256647680:/vllm-workspace/vllm-omni# bash examples/run_qwen_image.sh 
> INFO 12-18 15:52:10 [__init__.py:43] Available plugins for group vllm.platform_plugins:
> INFO 12-18 15:52:10 [__init__.py:45] - ascend -> vllm_ascend:register
> INFO 12-18 15:52:10 [__init__.py:48] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
> INFO 12-18 15:52:10 [__init__.py:217] Platform plugin ascend is activated
> /usr/local/python3.11.13/lib/python3.11/site-packages/torch/amp/autocast_mode.py:266: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
>   warnings.warn(
> Modular Diffusers is currently an experimental feature under active development. The API is subject to breaking changes in future releases.
> INFO 12-18 15:52:17 [importing.py:68] Triton not installed or not compatible; certain GPU-related functions will not be available.
> Traceback (most recent call last):
>   File "/usr/local/python3.11.13/bin/vllm", line 3, in <module>
>     from vllm_omni.entrypoints.cli.main import main
>   File "/vllm-workspace/vllm-omni/vllm_omni/__init__.py", line 23, in <module>
>     from .config import OmniModelConfig
>   File "/vllm-workspace/vllm-omni/vllm_omni/config/__init__.py", line 5, in <module>
>     from vllm_omni.config.model import OmniModelConfig
>   File "/vllm-workspace/vllm-omni/vllm_omni/config/model.py", line 34, in <module>
>     import vllm_omni.model_executor.models as me_models
>   File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/__init__.py", line 1, in <module>
>     from .qwen3_omni import Qwen3OmniMoeForConditionalGeneration
>   File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/qwen3_omni/__init__.py", line 1, in <module>
>     from .qwen3_omni import Qwen3OmniMoeForConditionalGeneration
>   File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/qwen3_omni/qwen3_omni.py", line 31, in <module>
>     from .qwen3_omni_moe_thinker import (
>   File "/vllm-workspace/vllm-omni/vllm_omni/model_executor/models/qwen3_omni/qwen3_omni_moe_thinker.py", line 74, in <module>
>     from vllm.model_executor.models.qwen2_5_vl import (
> ImportError: cannot import name 'Qwen2_5_VisionRotaryEmbedding' from 'vllm.model_executor.models.qwen2_5_vl' (/vllm-workspace/vllm/vllm/model_executor/models/qwen2_5_vl.py)
> [ERROR] 2025-12-18-15:52:17 (PID:5544, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
> ```

We haven't still upgraded yet. Please use the temporary solution before v0.12.0 releasing.

**Comment by min-star** [comment]
the same error
`ImportError: cannot import name 'Qwen2_5_VisionRotaryEmbedding' from 'vllm.model_executor.models.qwen2_5_vl'`

**Comment by gcanlin** [comment]
> the same error `ImportError: cannot import name 'Qwen2_5_VisionRotaryEmbedding' from 'vllm.model_executor.models.qwen2_5_vl'`

Please use vllm-omni v0.11.0rc1 with vllm-ascend v0.11.0rc2 for now. I'm trying to upgrade to vllm-omni with vllm-ascend v0.12.0rc1, which needs to take some time.

**Comment by min-star** [comment]
> > the same error `ImportError: cannot import name 'Qwen2_5_VisionRotaryEmbedding' from 'vllm.model_executor.models.qwen2_5_vl'`
> 
> Please use vllm-omni v0.11.0rc1 with vllm-ascend v0.11.0rc2 for now. I'm trying to upgrade to vllm-omni with vllm-ascend v0.12.0rc1, which needs to take some time.

Sorry, I didn't explain clearly. My environment is GPU, and I'm using VLLM 0.12.0. Which version of VLLM do I need to install?

**Comment by hsliuustc0106** [comment]
> > > the same error `ImportError: cannot import name 'Qwen2_5_VisionRotaryEmbedding' from 'vllm.model_executor.models.qwen2_5_vl'`
> > 
> > 
> > Please use vllm-omni v0.11.0rc1 with vllm-ascend v0.11.0rc2 for now. I'm trying to upgrade to vllm-omni with vllm-ascend v0.12.0rc1, which needs to take some time.
> 
> Sorry, I didn't explain clearly. My environment is GPU, and I'm using VLLM 0.12.0. Which version of VLLM do I need to install?

please check our quick start, for gpu, it should be ok with vllm0.12.0 and vllm-omni from main
