### PR TITLE
[CI] [non-CUDA] [ROCm] Fix `get_diffusion_attn_backend_cls() got an unexpected keyword argument 'allow_trtllm_default'`

### PR DESCRIPTION
**Pull request by tjtanaa**
PLEASE FILL IN THE PR DESCRIPTION HERE.

## Purpose

Fix error introduced by PR https://github.com/vllm-project/vllm-omni/pull/5283 . This error will also occur on all non-CUDA platform.

```log
2026-07-28 07:40:35 UTC
  File "/app/vllm-omni/vllm_omni/diffusion/attention/layer.py", line 85, in __init__
2026-07-28 07:40:35 UTC
    attn_backend_cls, spec = get_attn_backend_for_role(
2026-07-28 07:40:35 UTC
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-07-28 07:40:35 UTC
  File "/app/vllm-omni/vllm_omni/diffusion/attention/selector.py", line 146, in get_attn_backend_for_role
2026-07-28 07:40:35 UTC
    backend_cls = _cached_get_backend_cls(None, head_size, allow_trtllm_default)
2026-07-28 07:40:35 UTC
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-07-28 07:40:35 UTC
  File "/app/vllm-omni/vllm_omni/diffusion/attention/selector.py", line 64, in _cached_get_backend_cls
2026-07-28 07:40:35 UTC
    backend_cls_path = current_omni_platform.get_diffusion_attn_backend_cls(
2026-07-28 07:40:35 UTC
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-07-28 07:40:35 UTC
TypeError: RocmOmniPlatform.get_diffusion_attn_backend_cls() got an unexpected keyword argument 'allow_trtllm_default'
```

Affected test group: `mi325_1: Diffusion · Wan22 Test`

## Test Plan

**vLLM Version:**

**vLLM-Omni Commit:**

## Test Result

**BEFORE SUBMITTING:** read [CONTRIBUTING.md](https://github.com/vllm-project/vllm-omni/blob/main/CONTRIBUTING.md) and run the [precheck-pr skill](https://github.com/vllm-project/vllm-omni/blob/main/.claude/skills/precheck-pr/SKILL.md) with the code agent for a self-check against project conventions.
(anything written below this line will be removed by GitHub Actions)

### CODE REVIEW

**Comment by tjtanaa** [comment]
PTAL thank you @yenuo26 @hsliuustc0106 @congw729

File: vllm_omni/diffusion/attention/selector.py [hunk 1]
```diff
@@ -61,10 +61,13 @@ def _cached_get_backend_cls(
     """
     from vllm_omni.platforms import current_omni_platform
 
+    extra_kwargs = {}
+    if current_omni_platform.is_cuda():
```
Comment (david6666666) [inline vllm_omni/diffusion/attention/selector.py:65]: Can you add a focused selector regression test for a non-CUDA platform? This branch is the whole bug fix, but the affected AMD check is still red and the PR's Test Plan is empty.

Comment (tjtanaa) [reply vllm_omni/diffusion/attention/selector.py:65]: I will follow this PR to apply the changes. https://github.com/vllm-project/vllm-omni/pull/5476 Intel side has landed this.

@david6666666 so do you prefer if we land a full big PR that fixes all test cases? Because the fixes is a lot. This is just [1/N] for ROCm CI.
