### PR TITLE
[diffusion] honor pre-tokenized prompt ids in the BAGEL and Lance MoT pipelines

### PR DESCRIPTION
**Pull request by ruiling-smartbear**
## What this is

An increment for the BAGEL and Lance MoT pipelines, not a fix for the diffusion
stack. The stack-wide gap is #7855.

The diffusion stack does not honor `OmniCustomPrompt.prompt_ids`. There is no
central handling for pre-tokenized prompts, the diffusers adapter reduces every
request to text at `pipeline_diffusers_adapter.py:501-516`, and each native
pipeline reads the text on its own. Only HunyuanImage3 has an ids path. At the
same time `_is_empty_dp_prompt` accepts a request that carries only ids, so such
a request is dispatched and then silently generates unconditioned output.

This PR covers the two pipelines we needed, and nothing more:

- `pipeline_bagel.py`, the text-to-image path
- `pipeline_lance.py`, the text-to-video path

Everything else still behaves as described in #7855. In particular the Lance
tasks that condition through `_segment_strings` and `_raw_text_prefill` (image
edit, i2v, video edit, x2t) are untouched, and so is the diffusers adapter. An
ids-only request to any of those still returns a successful, unconditioned
result; making that an error instead, or honoring the ids everywhere, remains
open in #7855.

## What changed

- `vllm_omni/diffusion/utils/prompt_utils.py`: new `pre_tokenized_prompt_ids`
  and `pre_tokenized_negative_prompt_ids`. They read `prompt_ids` and
  `negative_prompt_ids`, with `prompt_token_ids` and `negative_prompt_token_ids`
  accepted as aliases because the executor's emptiness check and the existing
  HunyuanImage3 writer already use that spelling.
- `vllm_omni/diffusion/models/bagel/bagel_transformer.py`:
  `Bagel.prepare_prompts` now accepts an entry that is a `str` or a `list[int]`,
  which is the convention `OmniSingletonPrompt` already uses. A pre-tokenized
  entry is packed verbatim, with no bos/eos wrapper, because the caller owns the
  exact sequence.
- `vllm_omni/diffusion/models/bagel/pipeline_bagel.py` and
  `vllm_omni/diffusion/models/lance/pipeline_lance.py`: those two paths forward
  the ids when the request carries them, for the positive prompt and for the CFG
  negative prompt.

`LanceBagel.prepare_prompts` overrides the parent to expand scalar positions
into 3-axis mRoPE, and it forwards `*args, **kwargs`, so the pre-tokenized path
goes through that expansion as well. There is a test for it.

## Behavior

Additive. A request without ids takes exactly the path it took before.

For a bare caption the two paths agree. The text path builds
`bos + tokenizer.encode(text, add_special_tokens=False) + eos`, where `bos` is
`<|im_start|>` and `eos` is `<|im_end|>`, so a caller that sends that same
sequence through `prompt_ids` gets identical conditioning.

## Tests

New CPU tests, marked `core_model` and `cpu`:

- `tests/diffusion/utils/test_prompt_utils.py`: key lookup, the alias, the
  batched single-prompt form, absent and empty values, and the positive and
  negative keys staying separate.
- `tests/diffusion/models/bagel/test_pre_tokenized_prompt_ids.py`: `forward`
  forwards the ids to the generation context, the `cfg_img` context and the CFG
  negative prompt; the text path is unchanged without ids; `prepare_prompts`
  packs ids verbatim and matches the equivalent text.
- `tests/diffusion/models/lance/test_pre_tokenized_prompt_ids.py`:
  `LanceBagel.prepare_prompts` keeps the ids and still expands the positions to
  3-axis mRoPE; `_forward_t2v` forwards the ids, including for the CFG negative
  prompt, and still uses the text without ids.

Plus `tests/diffusion/models/bagel/test_negative_prompt.py` and
`tests/diffusion/models/lance/test_pipeline_lance.py`, which cover the paths this
touches.

## Verification

Run on CPU, from the branch checkout, against vllm 0.29.0 (what current `main`
needs; from vllm 0.28.0, importing `pipeline_bagel` fails with
`ImportError: cannot import name 'compute_layout_strides' from 'vllm.v1.kv_cache_interface'`,
which is unrelated to this change).

| target | result |
| --- | --- |
| `tests/diffusion/utils/test_prompt_utils.py` | 17 passed |
| `tests/diffusion/models/bagel/test_pre_tokenized_prompt_ids.py` | 6 passed |
| `tests/diffusion/models/lance/test_pre_tokenized_prompt_ids.py` | 5 passed |
| `tests/diffusion/models/bagel/test_negative_prompt.py` | 2 passed |
| `tests/diffusion/models/lance/test_pipeline_lance.py` | 20 passed |

Control: reverting only `vllm_omni/` to the parent commit, with the new tests
left in place, makes the new behaviour tests fail. They test the change rather
than passing on their own.

`ruff check` and `ruff format --check` are clean on all seven changed files.

### CODE REVIEW

**Comment by ruiling-smartbear** [comment]
Follow-up stacked on this branch, since it needs the scheduler/trajectory work here:
`fix/lance-conditioned-replay-export` (fork PR: https://github.com/ruiling-smartbear/vllm-omni/pull/1).

It carries two commits:

* a bug fix that this branch's replay path exposed - i2v and video edit resolved
  the video shape from the prompt's `extra_args` only, so a request that set
  `height` / `width` / `num_frames` on the sampling params (as `sana_video`'s i2v
  does) silently got this node's defaults (61 frames at 848x480), and both
  forwards rejected the media list that `multi_modal_data` carries while
  `_forward_image_edit` already normalized it. The shape mismatch is what a
  replay notices: 25440 tokens against the 10080 the requested shape implies.
* the export a conditioned replay needs: BAGEL's shared `forward_cache_update_vit`
  / `forward_cache_update_vae` and the Lance edit forwards can hand back the rows
  they prefilled, the text segments, the reference's per-axis positions, the
  latent block's positions/grid and the rotary anchor, for the trainer to
  reconstruct the context it cannot rebuild without a ViT or a VAE. It follows
  the protocol H3's Ref2VA replay already uses on the `rl` channel.

One interaction to flag: this branch prefills text-to-video from the caller's
token ids when it has them. The merge keeps that and restores the upstream
system-prompt/assistant-header segments for the no-ids case, because handing a
bare caption to `prepare_prompts` wraps it in bos/eos only and conditions the
model on `<|im_start|>caption<|im_end|>` with no task instruction. Callers that
pass ids own their template; a replay then shares the same text side by
construction.

I will retarget the companion PR to `main` once this one lands, so its diff is
the export alone. Verified end to end: with this stack applied, Lance
image-to-video, image edit and video edit each run two training steps of their
recipe with rollout/trainer log-prob differences of 5.7e-03, 5.6e-04 and 4.1e-05.

**Comment by ruiling-smartbear** [comment]
The RL half of this branch (the four forwards' scheduler/trajectory plus the rotary-anchor export) moved to #7907, which is standalone against main. This PR is now the prompt-id increment alone.

**Comment by ruiling-smartbear** [comment]
Self-review.

Additive by construction: a request without `prompt_ids` takes exactly the path it took before, and the ids path packs the caller's sequence verbatim with no bos/eos wrapper. The negative-prompt ids are read separately from the positive ones, and `prompt_token_ids` is accepted as an alias because the executor's emptiness check and the existing HunyuanImage3 writer already use that spelling.

**Tests** (CPU, vllm 0.29.0, branch checkout)
- new: `test_prompt_utils.py` 17 passed, `bagel/test_pre_tokenized_prompt_ids.py` 6 passed, `lance/test_pre_tokenized_prompt_ids.py` 5 passed
- pre-existing: `bagel/test_negative_prompt.py` 2 passed, `lance/test_pipeline_lance.py` 20 passed
- control: reverting `vllm_omni/` to the parent commit makes the new tests fail (exit 2 / 1 / 1), and restoring makes them pass again, so they test the change rather than passing on their own
- `ruff check` and `ruff format --check` clean on the changed files

**Scope**: BAGEL text-to-image and Lance text-to-video only. A request that carries ids and lands on any other diffusion path is still admitted and runs with an empty prompt; that is the stack-wide gap tracked in #7855.

The Lance RL-specific work that used to sit on this branch (caller scheduler and trajectory, rotary-anchor export) moved to #7907, which is standalone against main.

**Comment by ruiling-smartbear** [comment]
@wtomin @RuixiangMa @david6666666 - could you please take a look? The diffusion stack declares and admits `OmniCustomPrompt.prompt_ids`, but nothing under `vllm_omni/diffusion/` reads it, so a request that carries ids only reaches the text encoder with an empty prompt and returns a normal, unconditioned result. This PR covers BAGEL t2i and Lance t2v; the stack-wide gap (and the option of rejecting ids-only requests instead) is #7855.
